
server:
  port: 8762
spring:
  application:
    name: service-hi
eureka:
  client:
    service-url:
#      defaultZone: http://peer1:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
